import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../store';
import { fetchEvents, fetchProminentLocations } from '../api/locations-api';
import { attachImages, LocationEvent } from '../api/mock-data/events';
import { ProminentLocation } from '../api/mock-data/simplemaps-locations';
import { GetProvinces } from './discovery-store-helpers';

export interface DiscoveryState {
  completeLocations: ProminentLocation[];
  locations: any;
  search: string;
  userPosition: any;
  provinces: ProminentLocation[];
  selectedEvent: LocationEvent | null;
  events: LocationEvent[] | null;
  status: 'idle' | 'complete' | 'loading' | 'failed';
  displayContent: {
    cities: ProminentLocation[] | null;
    province: ProminentLocation | null;
  }
}

const initialState: DiscoveryState = {
  completeLocations: [],
  provinces: [],
  selectedEvent: null,
  events: null,
  locations: [],
  search: "",
  userPosition: "",
  status: 'idle',
  displayContent: {
    cities: null,
    province: null,
  }
};

export const FetchEventsAsync = createAsyncThunk("events/fetch", async () => {
  const response: string = await fetchEvents();
  return JSON.parse(response) as LocationEvent[];
})

export const FetchProminentLocationsAsync = createAsyncThunk("discovery/FetchLocationsAsync", async () => {
  const response: string = await fetchProminentLocations();
  return JSON.parse(response);
})

export const discoverySlice = createSlice({
  name: 'discovery',
  initialState,
  reducers: {
    setProvinces: (state: DiscoveryState, action: PayloadAction<ProminentLocation[]>) => {
      state.provinces = action.payload;
    },
    setUserPosition: (state: DiscoveryState, action: PayloadAction<any[]>) => {
      state.userPosition = action.payload;
    },
    setSearch: (state: DiscoveryState, action: PayloadAction<string>) => {
      state.search = action.payload
    },
    setProvinceCity: (state: DiscoveryState, action: PayloadAction<string>) => {
      // Find all locations with admin_name/province of action
      state.displayContent.cities = state.completeLocations.filter((location) => {
        if (location.admin_name.toLocaleLowerCase() === action.payload.toLocaleLowerCase()) {
          return location;
        }
      });

      console.log("STATE - reducers{setProvinceCity}", state.displayContent, state.completeLocations, action.payload);
    },
    setSelectedEvent: (state: DiscoveryState, action: PayloadAction<LocationEvent | null>) => {
      console.log("STATE - reducers{setSelectedEvent}", action.payload);
      state.selectedEvent = action.payload
    }
  },

  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(FetchProminentLocationsAsync.pending, (state: DiscoveryState) => {
        state.status = 'loading';
      })
      .addCase(FetchProminentLocationsAsync.fulfilled, (state: DiscoveryState, action: PayloadAction<ProminentLocation[]>) => {
        state.status = 'complete';
        state.completeLocations = action.payload;
        // Function to get unique provinces. Create a list of none duplicate provinces  
        state.provinces = GetProvinces(action.payload)
      })
      .addCase(FetchProminentLocationsAsync.rejected, (state: DiscoveryState) => {
        state.status = 'failed';
      })
      
      .addCase(FetchEventsAsync.pending, (state: DiscoveryState) => {
        state.status = 'loading';
      })
      .addCase(FetchEventsAsync.fulfilled, (state: DiscoveryState, action: PayloadAction<LocationEvent[]>) => {
        
        state.events = attachImages(action.payload);
        state.status = 'complete';
      })
      .addCase(FetchEventsAsync.rejected, (state: DiscoveryState) => {
        state.status = 'failed';
      })
  },
});

export const { setProvinces, setUserPosition, setSearch, setProvinceCity, setSelectedEvent } = discoverySlice.actions;

export const selectDiscovery = (state: RootState) => (state.discovery) ? state.discovery : initialState;
export const selectCompleteLocation = (state: RootState) => (state.discovery.completeLocations) ? state.discovery.completeLocations : initialState.completeLocations;
export const selectProvinces = (state: RootState) => (state.discovery.provinces) ? state.discovery.provinces : initialState.provinces;
export const selectLocations = (state: RootState) => (state.discovery.locations) ? state.discovery.locations : initialState.locations;
export const selectStatus = (state: RootState) => state.discovery.status;
export const selectDisplayContent = (state: RootState) => state.discovery.displayContent;
export const selectDisplayCities = (state: RootState) => state.discovery.displayContent.cities;
export const selectEvents = (state: RootState) => state.discovery.events;
export const selectedEvent = (state: RootState) => state.discovery.selectedEvent;

export default discoverySlice.reducer;
