/**
 * Reference: data found at: 
 * https://simplemaps.com/data/za-cities
 */

export type ProminentLocations = {
  admin_name: string,
  capital: string,
  city: string,
  country: string,
  iso2: string,
  lat: string,
  lng: string,
  population: string,
  population_proper: string,
  bg_image?: string,
}

export const prominentLocations: ProminentLocations[] = [
  {
    city: "Johannesburg",
    lat: "-26.2044",
    lng: "28.0416",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "admin",
    population: "4434827",
    population_proper: "4434827",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Vereeniging",
    lat: "-26.6736",
    lng: "27.9319",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "1074000",
    population_proper: "474681",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Pietermaritzburg",
    lat: "-29.5833",
    lng: "30.4167",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "KwaZulu-Natal",
    capital: "admin",
    population: "750845",
    population_proper: "490951",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Pretoria",
    lat: "-25.7464",
    lng: "28.1881",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "primary",
    population: "741651",
    population_proper: "741651",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Durban",
    lat: "-29.8583",
    lng: "31.0250",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "KwaZulu-Natal",
    capital: "",
    population: "595061",
    population_proper: "595061",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Cape Town",
    lat: "-33.9250",
    lng: "18.4250",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "primary",
    population: "433688",
    population_proper: "433688",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Welkom",
    lat: "-27.9831",
    lng: "26.7208",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Free State",
    capital: "",
    population: "431944",
    population_proper: "126079",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "East London",
    lat: "-33.0153",
    lng: "27.9116",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "",
    population: "338627",
    population_proper: "338627",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Randburg",
    lat: "-26.0936",
    lng: "28.0064",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "337053",
    population_proper: "337053",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Roodepoort",
    lat: "-26.1625",
    lng: "27.8725",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "326416",
    population_proper: "326416",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Port Elizabeth",
    lat: "-33.9581",
    lng: "25.6000",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "",
    population: "312392",
    population_proper: "312392",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Bloemfontein",
    lat: "-29.1000",
    lng: "26.2167",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Free State",
    capital: "primary",
    population: "256185",
    population_proper: "256185",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Centurion",
    lat: "-25.8603",
    lng: "28.1894",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "236580",
    population_proper: "236580",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Springs",
    lat: "-26.2547",
    lng: "28.4428",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "236083",
    population_proper: "186394",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Sandton",
    lat: "-26.1070",
    lng: "28.0517",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "222415",
    population_proper: "222415",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Polokwane",
    lat: "-23.9000",
    lng: "29.4500",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Limpopo",
    capital: "admin",
    population: "220045",
    population_proper: "123749",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Klerksdorp",
    lat: "-26.8667",
    lng: "26.6667",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "North West",
    capital: "",
    population: "178921",
    population_proper: "147804",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Rustenburg",
    lat: "-25.6667",
    lng: "27.2336",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "North West",
    capital: "",
    population: "165976",
    population_proper: "124064",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Kimberley",
    lat: "-28.7386",
    lng: "24.7586",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Northern Cape",
    capital: "admin",
    population: "165264",
    population_proper: "142089",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Bhisho",
    lat: "-32.8494",
    lng: "27.4381",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "admin",
    population: "160997",
    population_proper: "137287",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Benoni",
    lat: "-26.1883",
    lng: "28.3206",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "158777",
    population_proper: "158777",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "George",
    lat: "-33.9667",
    lng: "22.4500",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "157394",
    population_proper: "157394",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Middelburg",
    lat: "-25.7684",
    lng: "29.4783",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Mpumalanga",
    capital: "",
    population: "154706",
    population_proper: "93790",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Vryheid",
    lat: "-27.7694",
    lng: "30.7914",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "KwaZulu-Natal",
    capital: "",
    population: "150012",
    population_proper: "66717",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Potchefstroom",
    lat: "-26.7150",
    lng: "27.1033",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "North West",
    capital: "",
    population: "148804",
    population_proper: "148804",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Umtata",
    lat: "-31.5800",
    lng: "28.7900",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "",
    population: "137772",
    population_proper: "78663",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Brits",
    lat: "-25.6167",
    lng: "27.7667",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "North West",
    capital: "",
    population: "122497",
    population_proper: "39947",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Alberton",
    lat: "-26.2672",
    lng: "28.1219",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "121536",
    population_proper: "121536",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Upington",
    lat: "-28.4572",
    lng: "21.2425",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Northern Cape",
    capital: "",
    population: "121189",
    population_proper: "121189",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Paarl",
    lat: "-33.7242",
    lng: "18.9558",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "112045",
    population_proper: "112045",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Queenstown",
    lat: "-31.9000",
    lng: "26.8833",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "",
    population: "105309",
    population_proper: "87240",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Mmabatho",
    lat: "-25.8500",
    lng: "25.6333",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "North West",
    capital: "",
    population: "104428",
    population_proper: "76754",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Kroonstad",
    lat: "-27.6456",
    lng: "27.2317",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Free State",
    capital: "",
    population: "103992",
    population_proper: "72835",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Uitenhage",
    lat: "-33.7500",
    lng: "25.4000",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "",
    population: "103639",
    population_proper: "103639",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Bethal",
    lat: "-26.4500",
    lng: "29.4500",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Mpumalanga",
    capital: "",
    population: "101919",
    population_proper: "90450",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Worcester",
    lat: "-33.6450",
    lng: "19.4436",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "97098",
    population_proper: "97098",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Vanderbijlpark",
    lat: "-26.6992",
    lng: "27.8356",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "95840",
    population_proper: "95840",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Grahamstown",
    lat: "-33.2996",
    lng: "26.5200",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "",
    population: "91548",
    population_proper: "49083",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Standerton",
    lat: "-26.9500",
    lng: "29.2500",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Mpumalanga",
    capital: "",
    population: "74021",
    population_proper: "18093",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Brakpan",
    lat: "-26.2353",
    lng: "28.3700",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "73080",
    population_proper: "73080",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Thohoyandou",
    lat: "-22.9500",
    lng: "30.4833",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Limpopo",
    capital: "",
    population: "69453",
    population_proper: "69453",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Saldanha",
    lat: "-32.9978",
    lng: "17.9456",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "68284",
    population_proper: "6654",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Tzaneen",
    lat: "-23.8333",
    lng: "30.1667",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Limpopo",
    capital: "",
    population: "67245",
    population_proper: "16954",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Graaff-Reinet",
    lat: "-32.2522",
    lng: "24.5406",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "",
    population: "62896",
    population_proper: "3021",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Oudtshoorn",
    lat: "-33.5833",
    lng: "22.2000",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "61507",
    population_proper: "61507",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Mossel Bay",
    lat: "-34.1833",
    lng: "22.1333",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "59031",
    population_proper: "59031",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Port Shepstone",
    lat: "-30.7411",
    lng: "30.4547",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "KwaZulu-Natal",
    capital: "",
    population: "52793",
    population_proper: "21858",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Knysna",
    lat: "-34.0356",
    lng: "23.0489",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "51078",
    population_proper: "51078",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Vryburg",
    lat: "-26.9500",
    lng: "24.7333",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "North West",
    capital: "",
    population: "49588",
    population_proper: "13590",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Ladysmith",
    lat: "-28.5539",
    lng: "29.7825",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "KwaZulu-Natal",
    capital: "",
    population: "47375",
    population_proper: "47375",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Kuilsrivier",
    lat: "-34.0333",
    lng: "18.7000",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "46686",
    population_proper: "46686",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Beaufort West",
    lat: "-32.3500",
    lng: "22.5833",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "44737",
    population_proper: "11404",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Aliwal North",
    lat: "-30.7000",
    lng: "26.7000",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "",
    population: "44436",
    population_proper: "8410",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Volksrust",
    lat: "-27.3667",
    lng: "29.8833",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Mpumalanga",
    capital: "",
    population: "43378",
    population_proper: "7411",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Musina",
    lat: "-22.3381",
    lng: "30.0417",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Limpopo",
    capital: "",
    population: "42678",
    population_proper: "42678",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Vredenburg",
    lat: "-32.9000",
    lng: "17.9833",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "38382",
    population_proper: "38382",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Malmesbury",
    lat: "-33.4500",
    lng: "18.7333",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "35897",
    population_proper: "35897",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Lebowakgomo",
    lat: "-24.3050",
    lng: "29.5650",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Limpopo",
    capital: "",
    population: "33308",
    population_proper: "397",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Cradock",
    lat: "-32.1833",
    lng: "25.6167",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "",
    population: "32898",
    population_proper: "32898",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "De Aar",
    lat: "-30.6500",
    lng: "24.0167",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Northern Cape",
    capital: "",
    population: "32318",
    population_proper: "5021",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Ulundi",
    lat: "-28.3350",
    lng: "31.4161",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "KwaZulu-Natal",
    capital: "",
    population: "29132",
    population_proper: "29132",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Jeffrey’s Bay",
    lat: "-34.0333",
    lng: "24.9167",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Eastern Cape",
    capital: "",
    population: "27107",
    population_proper: "27107",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Lichtenburg",
    lat: "-26.1500",
    lng: "26.1667",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "North West",
    capital: "",
    population: "26338",
    population_proper: "26338",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Hermanus",
    lat: "-34.4167",
    lng: "19.3000",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Western Cape",
    capital: "",
    population: "25153",
    population_proper: "7396",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Carletonville",
    lat: "-26.3581",
    lng: "27.3981",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Gauteng",
    capital: "",
    population: "23000",
    population_proper: "23000",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Mahikeng",
    lat: "-25.8653",
    lng: "25.6442",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "North West",
    capital: "admin",
    population: "15117",
    population_proper: "15117",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  },
  {
    city: "Nelspruit",
    lat: "-25.4745",
    lng: "30.9703",
    country: "South Africa",
    iso2: "ZA",
    admin_name: "Mpumalanga",
    capital: "admin",
    population: "",
    population_proper: "",
    bg_image: `${process.env.PUBLIC_URL}/assets/image/location-background-images/location_01.jpg`
  }
]
